### ISSUE TITLE
Running your own server is severely underdocumented

### ISSUE THREAD

**Issue by w23** [openwrt/asu#1002]
(I don't mean it as a rant or an attack, please don't read it as such -- the tone just a limitation of my English, and lack of time to smoothen the cultural discrepancy edges. I do appreciate your effort on this project.)

Using the official server is impractical -- when I tried, I was 650-something in line, and it was barely moving, decreasing by one every 5-10 minutes or so.

And after three hours of trying to run my own server I must declare an utter defeat.

1. Apparently the LuCI plugin talks to the server directly from browser (that took 15 minutes of frantic tcpdumping to figure out). 
That runs into "mixed content" https issue, and can be trivially worked around in Firefox by clicking on the lock in the URL bar and disabling protection.
CORS is more painful -- I had to run the server behind nginx reverse-proxy with `add_header 'Access-Control-Allow-Origin' '*' always;` directive.
2. Then it will just run into a 404 wall of what ultimately, through a redirect or two, amounts to absent `overview.json`. I suspect that it is generated somehow through running `poetry run python3 misc/update_all_targets.py`. But it didn't work here. It just failed with thousands of messages like
```
...
INFO:     10.89.0.27:39372 - "GET /api/v1/update/23.05.2/bmips/bcm6362 HTTP/1.1" 403 Forbidden
INFO:     10.89.0.27:39372 - "GET /api/v1/update/23.05.2/bmips/bcm63268 HTTP/1.1" 403 Forbidden
INFO:     10.89.0.27:39372 - "GET /api/v1/update/23.05.2/bmips/bcm6368 HTTP/1.1" 403 Forbidden
INFO:     10.89.0.27:39372 - "GET /api/v1/update/23.05.2/bmips/bcm6358 HTTP/1.1" 403 Forbidden
...
```
Having no easy way to debug it (I am absolutely not familiar with neither python web stuff, nor podman or containers at all; found no easy way to iterate -- all changes to sources needed a full `podman kill && podman rm &&  podman-compose build`, a lengthy and annoying operation), I've tried playing around public dir mount. It seems that it's hardcoded essentially to `/app/public` in the sources, but `podman-compose.yml` mounts it at a different location depending on where the source was cloned into. This is where I ran out of time and could not continue further.

There's another thread #975 where @efahl was somehow able to do it. But the full steps are yet to be documented.

If I get more time to try it (somewhat unlikely, at this point I'm feeling like not falling into sunk-cost fallacy and just re-flashing the devices manually), I'll document my steps in this thread.

I'd appreciate if anyone also tried and has any insight.

**Comment by efahl** [comment]
Yeah, the lack of docs is one of the big items on my list.  I'll get back to you here, as soon as I get some time.  

In the meantime, try these changes in podman-compose.yml and see if they help:
```
...
services:
  server:
    image: "asu:latest"
    build:
      context: ./
      dockerfile: Containerfile
    restart: always
    environment:
      - REDIS_URL=redis://redis/
    ports:
      - "0.0.0.0:8000:8000"     <-- assuming you are using a local machine, this exposes it to the LAN no need for proxy
    volumes:
      - $PUBLIC_PATH:/app/public:rw,rshared   <-- I found this works better, must match below
    depends_on:
      - redis

  worker:
    image: "asu:latest"
    build:
      context: ./
      dockerfile: Containerfile
    restart: always
    command: rqworker --with-scheduler
    environment:
      - REDIS_URL=redis://redis/
    volumes:
      - $PUBLIC_PATH:/app/public:rw,rshared    <-- same as above
      - $CONTAINER_SOCK:$CONTAINER_SOCK:rw
    depends_on:
      - redis
...
```

Should mount the storage on the host in `./public` then if you log into the pods `podman exec -ti asu_worker_1 /bin/bash` and poke around, you should see the same files on both worker and server under `/app/public/`.  

The `misc/update_all_targets.py` needs some hackery to work with port 8000 (plus it does all versions and targets, so way to much for casual use).
